#!/bin/bash
# GCal Precision Mover — one-time installer for the update helper.
#
# Registers the native messaging host with Chrome so the extension's
# "Update now" button can run `git pull` in this folder and reload itself.
#
# The launcher + host are COPIED to a folder outside ~/Documents and the
# browser manifests point at that copy. Why: on macOS, Documents (and
# Desktop/Downloads) are TCC-protected — a browser without the "Documents
# Folder" permission can't even read a script there, so the host dies
# instantly and Chrome reports "Native host has exited." The installed copy
# always starts; if the browser still can't reach the repo for git, the host
# now replies with a clear permission error instead of dying silently.
#
# Usage:  bash install.sh
# Remove: bash install.sh --uninstall

set -euo pipefail

HOST_NAME="com.danielgodiksen.gpm_updater"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(dirname "$DIR")"

case "$(uname -s)" in
  Darwin)
    INSTALL_DIR="$HOME/Library/Application Support/GCalPrecisionMover"
    TARGETS=(
      "$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
      "$HOME/Library/Application Support/Google/Chrome Beta/NativeMessagingHosts"
      "$HOME/Library/Application Support/Google/Chrome Canary/NativeMessagingHosts"
      "$HOME/Library/Application Support/Chromium/NativeMessagingHosts"
      "$HOME/Library/Application Support/BraveSoftware/Brave-Browser/NativeMessagingHosts"
      "$HOME/Library/Application Support/Microsoft Edge/NativeMessagingHosts"
      "$HOME/Library/Application Support/Arc/User Data/NativeMessagingHosts"
      "$HOME/Library/Application Support/Vivaldi/NativeMessagingHosts"
    )
    ;;
  Linux)
    INSTALL_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/gcal-precision-mover"
    TARGETS=(
      "$HOME/.config/google-chrome/NativeMessagingHosts"
      "$HOME/.config/chromium/NativeMessagingHosts"
      "$HOME/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts"
      "$HOME/.config/microsoft-edge/NativeMessagingHosts"
      "$HOME/.config/vivaldi/NativeMessagingHosts"
    )
    ;;
  *)
    echo "Unsupported OS (Windows needs registry keys — see README)." >&2
    exit 1
    ;;
esac

if [[ "${1:-}" == "--uninstall" ]]; then
  for t in "${TARGETS[@]}"; do
    rm -f "$t/$HOST_NAME.json" && echo "Removed $t/$HOST_NAME.json" || true
  done
  rm -rf "$INSTALL_DIR" && echo "Removed $INSTALL_DIR"
  exit 0
fi

# Derive the extension ID from the "key" pinned in manifest.json.
EXT_ID="$(python3 - "$REPO/manifest.json" <<'PY'
import json, hashlib, base64, sys
key = json.load(open(sys.argv[1]))["key"]
h = hashlib.sha256(base64.b64decode(key)).hexdigest()[:32]
print("".join(chr(ord("a") + int(c, 16)) for c in h))
PY
)"

# Install the helper outside the (possibly TCC-protected) repo folder.
mkdir -p "$INSTALL_DIR"
cp "$DIR/gpm_host_launcher.sh" "$DIR/gpm_native_host.py" "$INSTALL_DIR/"
cat > "$INSTALL_DIR/gpm_host.conf" <<EOF
# Generated by install.sh — tells the update helper where the repo lives.
GPM_REPO="$REPO"
EOF
chmod +x "$INSTALL_DIR/gpm_host_launcher.sh" "$INSTALL_DIR/gpm_native_host.py"
LAUNCHER="$INSTALL_DIR/gpm_host_launcher.sh"
echo "Helper installed to: $INSTALL_DIR"

INSTALLED=0
for t in "${TARGETS[@]}"; do
  # Only install for browsers that exist on this machine.
  [[ -d "$(dirname "$t")" ]] || continue
  mkdir -p "$t"
  cat > "$t/$HOST_NAME.json" <<EOF
{
  "name": "$HOST_NAME",
  "description": "GCal Precision Mover update helper (git pull)",
  "path": "$LAUNCHER",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://$EXT_ID/"]
}
EOF
  echo "Registered: $t/$HOST_NAME.json"
  INSTALLED=1
done

if [[ "$INSTALLED" == "0" ]]; then
  echo "No Chrome profile folder found — is Chrome installed?" >&2
  exit 1
fi

echo
echo "Done. Extension ID: $EXT_ID"
echo "Reload the extension once (chrome://extensions → ↻), then the"
echo "'Update now' button in the popup will work."
echo
echo "If updates fail with a folder-permission error: System Settings →"
echo "Privacy & Security → Files & Folders → your browser → allow"
echo "'Documents Folder' (the repo lives in $REPO)."
